# Command to build docker-compose
# docker-compose build

# Command to run docker-compose
# docker-compose up

# Command to build and run
# docker-compose up --build

# The following warning message will be seen on Windows OS, and is fine:
# level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string."

version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "example"
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    environment:
      WAIT_HOSTS: db:5432, pgadmin:80
    ports:
      - "8080:5000"
    depends_on:
      - db
    volumes:
      - outputs:/app/outputs

volumes:
  postgres_data:
  pgadmin_data:
  outputs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/outputs
